apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvis-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kvis-backend
  template:
    metadata:
      labels:
        app: kvis-backend
    spec:
      serviceAccount: backend
      serviceAccountName: backend
      containers:
      - name: kvis-backend
        image: localhost:5000/kvis-backend:latest
        ports:
        - containerPort: 8082
        env:
        - name: BACKEND_PORT
          value: "8082"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-role-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: backend-role
subjects:
- kind: ServiceAccount
  name: backend
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["pvc"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["endpoints"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: backend-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backend-role
subjects:
- kind: ServiceAccount
  name: backend
  namespace: default



          # - name: KUBECONFIG
        #   value: "/etc/rancher/k3s/k3s.yaml"
        # volumeMounts:
        # - name: kubeconfig
        #   mountPath: /etc/rancher/k3s
        #   readOnly: true
      # volumes:
      # - name: kubeconfig
      #   hostPath:
      #     path: /etc/rancher/k3s
      #     type: Directory
      #   volumeMounts:
      #   - mountPath: "/usr/share/nginx/html"
      #     name: dummy-storage
      # volumes:
      # - name: dummy-storage
      #   persistentVolumeClaim:
      #     claimName: dummy-pvc