name: CI

on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  push:
    branches: ["**"]  # Matches all branches
  pull_request:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Build client Docker image
        run: docker build -t kvis-client:latest -f client/Dockerfile client

      - name: Build backend Docker image
        run: docker build -t kvis-backend:latest -f backend/Dockerfile backend

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v3
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-region: ${{ secrets.AWS_REGION }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # - name: Log in to Amazon ECR
      #   run: |
      #     aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

      # - name: Build the Docker image
      #   run: |
      #     docker build -t kvisWeb .

      # - name: Tag image
      #   run: |
      #     IMAGE_TAG=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/kvisWeb:latest
      #     docker tag kvisWeb:latest $IMAGE_TAG

      # - name: Push Docker image to Amazon ECR
      #   run: |
      #     IMAGE_TAG=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/kvisWeb:latest
      #     docker push $IMAGE_TAG